{
    "name":"Bahmni Custom",
    "version":"1.0",
    "author":"ThoughtWorks Technologies Pvt. Ltd.",
    "category":"PossibleCustom",
    "description":"Custom changes for possible environment",
    "depends": ["base","bahmni_internal_stock_move","bahmni_pharmacy_product","bahmni_purchase_extension","stock","purchase","account","web_d3_chart"],
    'data':['module_misc.xml','purchase_by_supplier_category_view.xml','sale_by_supplier_category_view.xml',
            'moving_inventory_analysis.xml','stock_out_report.xml','min_max_report.xml','security/ir.model.access.csv',
            'supplier_category_view.xml','kpi_sheet_report.xml','kpi_sheet_hospital.xml'],
    'demo':[],
    'auto_install':False,
    'application':True,
    'installable':True,
}